<?php
/* ══════════════════════════════════════════════════════════
   ALMA DE MAR · Catálogo inicial de la tienda
   ──────────────────────────────────────────────────────────
   Es la lista de precios de la marca, tal cual, para sembrar
   la tabla `productos` la primera vez. A partir de ahí manda
   la base de datos: lo que se edite en el panel NO se pisa al
   volver a ejecutar el instalador (se usa INSERT ... ON
   DUPLICATE KEY UPDATE solo sobre los campos de catálogo).

   Cada fila:
     [id, nombre, categoría, presentación, precio, descripción,
      nombre científico, precauciones, imagen, orden]

   `imagen` es un archivo dentro de assets/img/tienda/, nombrado
   con el id del producto. Las 41 fichas del Catálogo 2026 traen la
   suya, compuesta con el botánico y el frasco que vienen en el PDF.
   Lo que no tiene foto propia usa la de su categoría.

   El peso y las medidas NO van aquí: los pone el perfil de la
   categoría en api/envios.php, y solo se capturan a mano en el
   panel cuando una pieza se sale del molde.
   ══════════════════════════════════════════════════════════ */

declare(strict_types=1);

/* Los grupos de la tienda, en el orden en que salen en la página. */
function categoriasTienda(): array {
    return [
        ['id' => 'aceites',     'titulo' => 'Aceites esenciales',   'nota' => '10 ml',  'imagen' => 'aceites.jpg'],
        ['id' => 'sinergias',   'titulo' => 'Sinergias',            'nota' => 'Mezclas con propósito', 'imagen' => 'sinergias.jpg'],
        ['id' => 'inhaladores', 'titulo' => 'Inhaladores nasales',  'nota' => '1.5 ml', 'imagen' => 'inhaladores.jpg'],
        ['id' => 'brisas',      'titulo' => 'Brisas y repelente',   'nota' => '125 ml', 'imagen' => 'brisas.jpg'],
        ['id' => 'masaje',      'titulo' => 'Aceites para masaje',  'nota' => '250 ml', 'imagen' => 'masaje.jpg'],
        ['id' => 'vehiculares', 'titulo' => 'Aceites vehiculares',  'nota' => '250 ml', 'imagen' => 'aceites-coleccion.jpg'],
        ['id' => 'velas8',      'titulo' => 'Velas',                'nota' => '8 oz',   'imagen' => ''],
        ['id' => 'velas4',      'titulo' => 'Velas',                'nota' => '4 oz',   'imagen' => ''],
    ];
}

function catalogoInicial(): array {
    return [
    ['ae-naranja', 'Naranja', 'aceites', '10 ml', 340,
     '',
     '', '', '', 10],
    ['ae-toronja', 'Toronja', 'aceites', '10 ml', 380,
     '',
     '', '', '', 11],
    ['ae-mandarina', 'Mandarina', 'aceites', '10 ml', 480,
     '',
     '', '', '', 12],
    ['ae-limon', 'Limón', 'aceites', '10 ml', 380,
     '',
     '', '', '', 13],
    ['ae-bergamota', 'Bergamota', 'aceites', '10 ml', 400,
     'Este aceite tiene potentes efectos antidepresivos, ansiolíticos, antibacterianos y antiinflamatorios. Es muy apreciado en aromaterapia para equilibrar las emociones y mejorar el ánimo. También se usa para afecciones de la piel como acné y eccema. Combina muy bien con lavanda, neroli, incienso, salvia y ylang ylang.',
     'Citrus bergamia', 'Usar solo en su versión “bergapten free” si se aplicará sobre la piel. Altamente fotosensibilizante. No usar durante el embarazo ni en niños menores de 6 años. Diluir bien antes de aplicar tópicamente.', 'ae-bergamota.jpg', 14],
    ['ae-lima', 'Lima', 'aceites', '10 ml', 380,
     '',
     '', '', '', 15],
    ['ae-albahaca', 'Albahaca', 'aceites', '10 ml', 340,
     '',
     '', '', '', 16],
    ['ae-anis', 'Anís', 'aceites', '10 ml', 480,
     '',
     '', '', '', 17],
    ['ae-clavo', 'Clavo', 'aceites', '10 ml', 380,
     'Con un alto contenido de eugenol, el aceite de clavo es un potente analgésico, antiséptico, antibacteriano y antioxidante. Se utiliza especialmente para aliviar dolores dentales, infecciones y como estimulante inmunológico. Combina bien con canela, naranja, incienso, albahaca, ylang ylang.',
     'Syzygium aromaticum', 'Irritante para piel y mucosas. Usar siempre diluido. No aplicar en embarazadas ni en bebés. Evitar uso prolongado o en personas con problemas hepáticos.', 'ae-clavo.jpg', 18],
    ['ae-canela', 'Canela', 'aceites', '10 ml', 380,
     '',
     '', '', '', 19],
    ['ae-curcuma', 'Cúrcuma', 'aceites', '10 ml', 500,
     '',
     '', '', '', 20],
    ['ae-romero', 'Romero', 'aceites', '10 ml', 380,
     'Este aceite es ideal para estimular la memoria, aliviar dolores musculares y mejorar la circulación. Tiene propiedades analgésicas, antisépticas, expectorantes y tónicas. Es útil en productos capilares por su acción sobre el cuero cabelludo. Combina muy bien con menta, lavanda, limón, toronja y eucalipto.',
     'Rosmarinus officinalis', 'Evitar durante el embarazo, especialmente en el primer trimestre. No usar en personas con epilepsia o hipertensión. No aplicar cerca de ojos ni en niños menores de 6 años.', 'ae-romero.jpg', 21],
    ['ae-menta', 'Menta', 'aceites', '10 ml', 380,
     '',
     '', '', '', 22],
    ['ae-hierbabuena', 'Hierbabuena', 'aceites', '10 ml', 500,
     '',
     '', '', '', 23],
    ['ae-lemongrass', 'Lemongrass', 'aceites', '10 ml', 380,
     '',
     '', '', '', 24],
    ['ae-jengibre', 'Jengibre', 'aceites', '10 ml', 560,
     '',
     '', '', '', 25],
    ['ae-oregano', 'Orégano', 'aceites', '10 ml', 540,
     '',
     '', '', '', 26],
    ['ae-cardamomo', 'Cardamomo', 'aceites', '10 ml', 780,
     '',
     '', '', '', 27],
    ['ae-enebro', 'Enebro', 'aceites', '10 ml', 700,
     '',
     '', '', '', 28],
    ['ae-laurel', 'Laurel', 'aceites', '10 ml', 780,
     '',
     '', '', '', 29],
    ['ae-pimienta-negra', 'Pimienta negra', 'aceites', '10 ml', 780,
     '',
     '', '', '', 30],
    ['ae-limon-italiano', 'Limón italiano', 'aceites', '10 ml', 800,
     '',
     '', '', '', 31],
    ['ae-salvia', 'Salvia', 'aceites', '10 ml', 540,
     '',
     '', '', '', 32],
    ['ae-tomillo', 'Tomillo', 'aceites', '10 ml', 380,
     '',
     '', '', '', 33],
    ['ae-eucalipto', 'Eucalipto', 'aceites', '10 ml', 380,
     '',
     '', '', '', 34],
    ['ae-geranio', 'Geranio', 'aceites', '10 ml', 540,
     'Este aceite es equilibrante hormonal, antidepresivo, astringente y antiinflamatorio. Se usa para cuidar la piel, mejorar el estado de ánimo y regular el ciclo menstrual. Tiene un aroma floral y dulce. Combina muy bien con lavanda, rosa, bergamota, incienso y cítricos.',
     'Pelargonium graveolens', 'Aunque es suave, puede causar sensibilidad cutánea en algunas personas. Evitar durante el primer trimestre del embarazo. Siempre hacer prueba de parche antes de uso tópico.', 'ae-geranio.jpg', 35],
    ['ae-rosas', 'Rosa', 'aceites', '10 ml', 1000,
     'De aroma profundo y floral, el aceite de rosa es uno de los más preciados por sus propiedades afrodisíacas, antidepresivas, cicatrizantes y regeneradoras. Apoya el bienestar emocional, la autoestima y el cuidado de la piel madura o sensible. Combina excelente con sándalo, geranio, ylang ylang, neroli e incienso.',
     'Rosa damascena', 'Generalmente bien tolerado, pero puede causar sensibilidad en pieles muy reactivas. Es un aceite costoso, por lo que suele estar diluido; revisar concentración antes de uso. No usar puro en bebés.', 'ae-rosas.jpg', 36],
    ['ae-lavanda', 'Lavanda', 'aceites', '10 ml', 380,
     'Uno de los aceites más versátiles, con propiedades calmantes, analgésicas, antiinflamatorias, cicatrizantes y ansiolíticas. Se usa para inducir el sueño, aliviar el estrés, tratar quemaduras, picaduras y problemas de piel. Combina bien con casi todos los aceites, especialmente romero, menta, incienso, geranio y naranja.',
     'Lavandula angustifolia', 'Generalmente seguro incluso en niños. Aun así, evitar contacto con ojos o mucosas. Puede causar irritación en personas extremadamente sensibles o alérgicas a las plantas de la familia Lamiaceae.', 'ae-lavanda.jpg', 37],
    ['ae-ylang-ylang', 'Ylang ylang', 'aceites', '10 ml', 500,
     'Este aceite floral tiene propiedades afrodisíacas, antidepresivas, hipotensoras y relajantes. Ayuda a reducir el estrés, equilibrar las emociones y mejorar el ánimo. También se usa para el cuidado del cabello y la piel. Combina muy bien con rosa, bergamota, jazmín, sándalo y naranja.',
     'Cananga odorata', 'Usar en pequeñas cantidades, ya que su aroma intenso puede causar dolor de cabeza o náuseas. Evitar en hipotensos. Realizar siempre prueba de sensibilidad antes de aplicarlo sobre la piel.', 'ae-ylang-ylang.jpg', 38],
    ['ae-incienso', 'Incienso', 'aceites', '10 ml', 780,
     '',
     '', '', '', 39],
    ['ae-sandalo', 'Sándalo', 'aceites', '10 ml', 540,
     '',
     '', '', '', 40],
    ['ae-cedro', 'Cedro', 'aceites', '10 ml', 380,
     '',
     '', '', '', 41],
    ['ae-cipres', 'Ciprés', 'aceites', '10 ml', 380,
     'Con un aroma fresco y amaderado, este aceite es astringente, diurético, tonificante y calmante. Es útil en tratamientos circulatorios, varices, retención de líquidos y para superar duelos o transiciones. Combina bien con limón, lavanda, enebro, cedro y geranio.',
     'Cupressus sempervirens', 'No se recomienda durante el embarazo. Puede causar sensibilidad cutánea si se aplica sin diluir. Evitar contacto con ojos y mucosas.', 'ae-cipres.jpg', 42],
    ['ae-pino-siberiano', 'Pino siberiano', 'aceites', '10 ml', 500,
     '',
     '', '', '', 43],
    ['ae-arbol-de-te', 'Árbol de té', 'aceites', '10 ml', 380,
     '',
     '', '', '', 44],
    ['ae-patchouli', 'Patchouli', 'aceites', '10 ml', 500,
     '',
     '', '', '', 45],
    ['ae-citronela', 'Citronela', 'aceites', '10 ml', 340,
     '',
     '', '', '', 46],
    ['ae-melissa', 'Melissa', 'aceites', '10 ml', 780,
     '',
     '', '', '', 47],
    ['ae-mirra', 'Mirra', 'aceites', '10 ml', 700,
     '',
     '', '', '', 48],
    ['ae-neroli', 'Neroli', 'aceites', '10 ml', 780,
     '',
     '', '', '', 49],
    ['ae-manzanilla-alemana', 'Manzanilla alemana', 'aceites', '10 ml', 1200,
     '',
     '', '', '', 50],
    ['ae-palo-santo', 'Palo santo', 'aceites', '10 ml', 780,
     'Con propiedades purificadoras, antiinflamatorias y energéticamente protectoras, este aceite es ideal para la meditación, aliviar tensiones y limpiar ambientes. Su aroma es cálido, amaderado y ligeramente cítrico. Combina bien con incienso, mirra, cedro, lavanda y cítricos.',
     'Bursera graveolens', 'No se recomienda en mujeres embarazadas. Puede causar sensibilidad cutánea en algunas personas. Siempre realizar prueba de parche antes de uso tópico.', 'ae-palo-santo.jpg', 51],
    ['ae-vetiver', 'Vetiver', 'aceites', '10 ml', 800,
     '',
     '', '', '', 52],
    ['si-respiracion', 'Respiración', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 10],
    ['si-dulces-suenos', 'Dulces sueños', 'sinergias', '10 ml', 430,
     'Contiene: Lavanda, naranja y mandarina. Esta sinergia calmante y reconfortante favorece un descanso profundo y reparador. Ayuda a relajar el sistema nervioso, disminuir la ansiedad y promover un ambiente de paz ideal para dormir. Su aroma es dulce, floral y suave. Ideal para difusor en la noche o en roll-on en muñecas y sienes.',
     '', 'Evitar en piel expuesta al sol (por la naranja y mandarina). No aplicar cerca de los ojos. Usar siempre diluido en niños.', 'si-dulces-suenos.jpg', 11],
    ['si-vitalidad', 'Vitalidad', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 12],
    ['si-inhala', 'Inhala +', 'sinergias', '10 ml', 430,
     'Contiene: Menta, lavanda y limón. Sinergia respiratoria que despeja las vías nasales, relaja el pecho y ayuda a respirar mejor. Combinando frescura y calma, es ideal para difusor, inhalación directa o para acompañar ejercicios respiratorios. Aroma equilibrado entre herbal y cítrico.',
     '', 'Fotosensibilizante. No aplicar cerca de ojos ni mucosas. No usar en niños pequeños ni en embarazadas.', 'si-inhala.jpg', 13],
    ['si-articulaciones', 'Articulaciones', 'sinergias', '10 ml', 430,
     'Contiene: Clavo, eucalipto y lavanda. Diseñada para aliviar molestias articulares, esta mezcla posee propiedades antiinflamatorias, analgésicas y relajantes. Útil en masajes localizados sobre rodillas, hombros, codos o muñecas con dolor o rigidez. Su aroma es cálido, herbal y ligeramente picante.',
     '', 'No usar en embarazadas ni en menores de 10 años. El clavo puede ser dermocáustico si no se diluye. Evitar mucosas y zonas irritadas.', 'si-articulaciones.jpg', 14],
    ['si-inmune', 'Inmune', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 15],
    ['si-despierta', 'Despierta', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 16],
    ['si-dolor-de-cabeza', 'Dolor de cabeza', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 17],
    ['si-armonia-y-bienestar', 'Armonía y bienestar', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 18],
    ['si-analgesia', 'Analgesia', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 19],
    ['si-concentracion', 'Concentración', 'sinergias', '10 ml', 440,
     'Contiene: Anís, cedro y lavanda. Esta sinergia mejora la claridad mental, la memoria y el enfoque. Ideal para periodos de estudio, trabajo intelectual o meditación enfocada. Su aroma es suave, ligeramente dulce con toques amaderados. Puede usarse en difusor o aplicado diluido en sienes o muñecas.',
     '', 'Evitar durante el embarazo. No aplicar cerca de ojos o mucosas. Usar con precaución en personas con presión alta o epilepsia.', 'si-concentracion.jpg', 20],
    ['si-mas-cabello', 'Más cabello', 'sinergias', '10 ml', 440,
     '',
     '', '', '', 21],
    ['si-fem', 'Fem', 'sinergias', '10 ml', 500,
     'Contiene: Salvia, geranio, lavanda y bergamota. Sinergia especialmente pensada para apoyar el bienestar femenino. Equilibra el sistema hormonal, calma los síntomas del síndrome premenstrual y promueve la conexión con la energía femenina. Su aroma es floral, herbal y ligeramente dulce. Ideal para usar en difusor o en aplicación tópica diluida sobre el abdomen o muñecas.',
     '', 'No usar durante el embarazo ni en niñas menores de 12 años. Fotosensibilizante por la bergamota. Evitar uso prolongado sin supervisión.', 'si-fem.jpg', 22],
    ['si-antioxidante', 'Antioxidante', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 23],
    ['si-super-boost', 'Súper boost', 'sinergias', '10 ml', 430,
     '',
     '', '', '', 24],
    ['si-serenidad', 'Serenidad', 'sinergias', '10 ml', 500,
     '',
     '', '', '', 25],
    ['si-redu-c', 'Redu-C', 'sinergias', '50 ml', 600,
     'Contiene: Toronja, ciprés, limón. Apoya procesos de reducción de grasa localizada, retención de líquidos y celulitis. Estimula el sistema linfático y mejora la tonicidad. Aplicar diluido con masajes ascendentes.',
     '', 'Fotosensibilizante. No usar en embarazadas ni en pieles reactivas. Evitar exposición solar tras su uso.', 'si-redu-c.jpg', 26],
    ['si-varices', 'Várices', 'sinergias', '50 ml', 600,
     'Contiene: Ciprés, menta, romero, limón. Estimula la circulación, alivia la pesadez y reduce la inflamación de las piernas. Ideal en masajes diluidos desde los pies hacia arriba. Aroma fresco y herbal.',
     '', 'No usar durante embarazo ni en piel lesionada. Fotosensibilizante. Evitar en casos de hipertensión sin supervisión.', 'si-varices.jpg', 27],
    ['si-digest', 'Digest', 'sinergias', '10 ml', 560,
     '',
     '', '', '', 28],
    ['si-mas-barba', 'Más barba', 'sinergias', '10 ml', 400,
     '',
     '', '', '', 29],
    ['si-enfoque', 'Enfoque', 'sinergias', '10 ml', 560,
     '',
     '', '', '', 30],
    ['si-slim', 'Slim', 'sinergias', '10 ml', 580,
     '',
     '', '', '', 31],
    ['si-serum-facial', 'Sérum facial', 'sinergias', '30 ml', 780,
     'Contiene: Rosa mosqueta, anís, incienso, geranio. Tratamiento facial regenerador, ideal para piel madura, manchas o líneas de expresión. Aporta elasticidad, firmeza y luminosidad. Aroma floral y ligeramente especiado.',
     '', 'No usar en embarazo. Realizar prueba de parche. Evitar en piel lesionada o sensible.', 'si-serum-facial.jpg', 32],
    ['si-pasion', 'Pasión', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 33],
    ['si-amor', 'Amor', 'sinergias', '10 ml', 660,
     'Contiene: Rosa, geranio, mandarina, ylang ylang y sándalo. Una sinergia envolvente y armoniosa que despierta el amor propio y fortalece los vínculos afectivos. Trabaja sobre el chakra corazón (Anahata), promoviendo equilibrio emocional, sensibilidad y empatía. Su aroma es floral, dulce, cálido y sensual.',
     '', 'Fotosensibilizante. No aplicar sin diluir. Evitar la exposición solar directa después de su uso tópico. Usar con precaución durante el embarazo.', 'si-amor.jpg', 34],
    ['si-motivacion', 'Motivación', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 35],
    ['si-paz', 'Paz', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 36],
    ['si-transformacion', 'Transformación', 'sinergias', '10 ml', 700,
     '',
     '', '', '', 37],
    ['si-alegria', 'Alegría', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 38],
    ['si-aura', 'Aura', 'sinergias', '10 ml', 780,
     'Contiene: Ylang ylang, rosas, melissa, sándalo, geranio. Mezcla elevada y espiritual que promueve la expansión del campo energético, la conexión con lo sutil y el amor incondicional. Ideal para meditaciones, rituales o armonización de espacios y personas. Trabaja sobre el chakra corona (Sahasrara) y el chakra corazón (Anahata). Aroma floral, suave, dulce y etéreo.',
     '', 'Usar diluido. No aplicar en piel expuesta al sol. Evitar en embarazo y personas con presión baja.', 'si-aura.jpg', 39],
    ['si-proteccion', 'Protección', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 40],
    ['si-abundancia', 'Abundancia', 'sinergias', '10 ml', 500,
     '',
     '', '', '', 41],
    ['si-zen', 'Zen', 'sinergias', '10 ml', 600,
     '',
     '', '', '', 42],
    ['v8-limon-satin', 'Limón Satín', 'velas8', '8 oz', 450,
     '',
     '', '', '', 10],
    ['v8-abrazo-al-alma', 'Abrazo al alma', 'velas8', '8 oz', 525,
     '',
     '', '', '', 11],
    ['v8-paz', 'Paz', 'velas8', '8 oz', 525,
     '',
     '', '', '', 12],
    ['v8-dulce-hogar', 'Dulce Hogar', 'velas8', '8 oz', 450,
     '',
     '', '', '', 13],
    ['v8-viento-de-otono', 'Viento de otoño', 'velas8', '8 oz', 450,
     '',
     '', '', '', 14],
    ['v8-estela-de-verano', 'Estela de verano', 'velas8', '8 oz', 450,
     '',
     '', '', '', 15],
    ['v8-entre-flores', 'Entre flores', 'velas8', '8 oz', 525,
     '',
     '', '', '', 16],
    ['v8-luz-de-eucalipto', 'Luz de eucalipto', 'velas8', '8 oz', 450,
     '',
     '', '', '', 17],
    ['v8-media-noche', 'Media noche', 'velas8', '8 oz', 450,
     '',
     '', '', '', 18],
    ['v8-himalaya', 'Himalaya', 'velas8', '8 oz', 450,
     '',
     '', '', '', 19],
    ['v8-astral', 'Astral', 'velas8', '8 oz', 525,
     '',
     '', '', '', 20],
    ['v8-mediterraneo', 'Mediterráneo', 'velas8', '8 oz', 525,
     '',
     '', '', '', 21],
    ['v4-limon-satin', 'Limón Satín', 'velas4', '4 oz', 270,
     '',
     '', '', '', 10],
    ['v4-abrazo-al-alma', 'Abrazo al alma', 'velas4', '4 oz', 295,
     '',
     '', '', '', 11],
    ['v4-paz', 'Paz', 'velas4', '4 oz', 295,
     '',
     '', '', '', 12],
    ['v4-dulce-hogar', 'Dulce Hogar', 'velas4', '4 oz', 270,
     '',
     '', '', '', 13],
    ['v4-viento-de-otono', 'Viento de otoño', 'velas4', '4 oz', 270,
     '',
     '', '', '', 14],
    ['v4-estela-de-verano', 'Estela de verano', 'velas4', '4 oz', 270,
     '',
     '', '', '', 15],
    ['v4-entre-flores', 'Entre flores', 'velas4', '4 oz', 295,
     '',
     '', '', '', 16],
    ['v4-luz-de-eucalipto', 'Luz de eucalipto', 'velas4', '4 oz', 270,
     '',
     '', '', '', 17],
    ['v4-media-noche', 'Media noche', 'velas4', '4 oz', 270,
     '',
     '', '', '', 18],
    ['v4-himalaya', 'Himalaya', 'velas4', '4 oz', 270,
     '',
     '', '', '', 19],
    ['v4-astral', 'Astral', 'velas4', '4 oz', 295,
     '',
     '', '', '', 20],
    ['v4-mediterraneo', 'Mediterráneo', 'velas4', '4 oz', 295,
     '',
     '', '', '', 21],
    ['ma-dulces-suenos', 'Dulces sueños', 'masaje', '240 ml', 450,
     'Contiene: lavanda, naranja, mandarina y aceite de almendras dulces. Una caricia para el alma antes de dormir. Este aceite para masaje promueve el descanso profundo y la relajación emocional. Perfecto para aplicar en espalda, cuello o pies antes de acostarte. Su aroma suave, floral y dulce envuelve los sentidos y crea una atmósfera cálida, pacífica y amorosa.',
     '', 'Puede causar fotosensibilidad. Usar diluido. Evitar en embarazo o en niños pequeños.', 'ma-dulces-suenos.jpg', 10],
    ['ma-analgesia', 'Analgesia', 'masaje', '240 ml', 450,
     'Contiene: lavanda, eucalipto, romero, menta y aceite de almendras dulces. Alivia el cuerpo y calma el malestar físico. Este aceite está diseñado para masajes en zonas con tensión, contracturas o dolor muscular. Su efecto es refrescante, antiinflamatorio y relajante. Ideal para después del ejercicio o jornadas exigentes. Su aroma herbal y mentolado favorece también la liberación mental del estrés acumulado.',
     '', 'Puede causar fotosensibilidad. Usar diluido. Evitar en embarazo o en niños pequeños.', 'ma-analgesia.jpg', 11],
    ['ma-despierta', 'Despierta', 'masaje', '240 ml', 450,
     'Contiene: limón, eucalipto y aceite de almendras dulces. Energía en forma de masaje. Este aceite revitalizante ayuda a activar el cuerpo, despejar la mente y mejorar la concentración. Ideal para masajes matutinos o para aplicar en la espalda y brazos cuando se necesita un empujón de ánimo. Su aroma fresco y cítrico transforma el ambiente y renueva tu energía vital.',
     '', 'Puede causar fotosensibilidad. Usar diluido. Evitar en embarazo o en niños pequeños.', 'ma-despierta.jpg', 12],
    ['br-dulces-suenos', 'Dulces sueños', 'brisas', '125 ml', 285,
     'Contiene: naranja, mandarina y lavanda. Su aroma suave, dulce y relajante ayuda a crear un ambiente propicio para el descanso profundo. Ideal para armonizar el estado emocional antes de dormir, disminuir tensiones acumuladas del día y favorecer rutinas nocturnas más tranquilas. Perfecta para usar en habitación, almohada, ropa de cama o espacios donde se busca calma y desconexión.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-dulces-suenos.jpg', 10],
    ['br-armonia-y-bienestar', 'Armonía y bienestar', 'brisas', '125 ml', 285,
     'Contiene: limón, naranja, bergamota, toronja y mandarina. Su aroma cítrico brillante y alegre ayuda a elevar el estado de ánimo, fomentar felicidad interna y equilibrar el ambiente con una vibra fresca, optimista y ligera. Ideal para espacios sociales, oficinas, áreas comunes y para renovar energía emocional durante el día. Perfecta para quienes buscan una sensación inmediata de luz y bienestar.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-armonia-y-bienestar.jpg', 11],
    ['br-serenidad', 'Serenidad', 'brisas', '125 ml', 330,
     'Contiene: lavanda, cedro, mandarina y albahaca. Su aroma herbal-cítrico con matices amaderados ayuda a equilibrar emociones, disminuir la sensación de carga mental y promover una sensación profunda de calma interior. Ideal para meditación, relajación, lectura y espacios donde se busca armonía emocional. Perfecta para momentos en los que necesitas bajar revoluciones sin perder claridad.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-serenidad.jpg', 12],
    ['br-despierta', 'Despierta', 'brisas', '125 ml', 285,
     'Contiene: limón y eucalipto. Su aroma fresco, cítrico y estimulante ayuda a activar la energía, aclarar la mente y favorecer la concentración. Ideal para iniciar el día con vitalidad, apoyar momentos de enfoque y crear ambientes dinámicos que impulsen la productividad. Perfecta para usar por las mañanas, en oficina o durante trabajo creativo.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-despierta.jpg', 13],
    ['br-proteccion', 'Protección', 'brisas', '125 ml', 330,
     'Contiene: clavo, canela, eucalipto, romero y limón. Su aroma especiado, herbal y refrescante ayuda a depurar la energía emocional del ambiente, elevar la sensación de seguridad interna y crear un campo aromático protector. Ideal para momentos de estrés, cambios energéticos, exceso de convivencia social o cuando se desea limpiar y renovar espacios de carga emocional.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-proteccion.jpg', 14],
    ['br-abundancia', 'Abundancia', 'brisas', '125 ml', 285,
     'Contiene: lavanda, cedro y canela. Su aroma cálido, envolvente y reconfortante fomenta una sensación de expansión emocional y mental, ayuda a elevar la confianza personal y atraer ambientes de apertura y fluidez energética. Ideal para rituales de intención, trabajo personal y espacios donde se desea promover prosperidad, inspiración y buena energía.',
     '', 'No aplicar directamente sobre piel, ojos o heridas. Evitar contacto con mascotas y bebés menores de 1 año directamente (aplicar solo en ambiente).', 'br-abundancia.jpg', 15],
    ['br-repelente-adios-mosqu', 'Repelente adiós mosquitos', 'brisas', '125 ml', 300,
     'Brisa repelente de aceites esenciales, sin ingredientes sintéticos agresivos.',
     '', '', '', 16],
    ['in-dolor-de-cabeza', 'Dolor de cabeza', 'inhaladores', '1.5 ml', 150,
     'Contiene: Menta, eucalipto, anís y limón. Una mezcla con propiedades analgésicas, antiinflamatorias y refrescantes que ayuda a aliviar dolores de cabeza, migrañas y tensiones causadas por el estrés, la fatiga o cambios hormonales.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-dolor-de-cabeza.jpg', 10],
    ['in-respiracion', 'Respiración', 'inhaladores', '1.5 ml', 150,
     'Contiene: Eucalipto, menta, árbol de té, limón. Una mezcla potente que ayuda a abrir las vías respiratorias, reducir la congestión y promover una sensación de aire limpio. Ideal para momentos de resfriado, alergias o cuando se busca una respiración más libre.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-respiracion.jpg', 11],
    ['in-despierta', 'Despierta con energía', 'inhaladores', '1.5 ml', 150,
     'Contiene: Limón y eucalipto. Una mezcla energizante y revitalizante que ayuda a iniciar el día con claridad y enfoque. Estimula la mente, favorece una respiración más libre y contribuye a reducir la fatiga mental.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-despierta.jpg', 12],
    ['in-dulces-suenos', 'Dulces sueños', 'inhaladores', '1.5 ml', 150,
     'Contiene: Lavanda, naranja y mandarina. Una mezcla calmante que ayuda a relajar el sistema nervioso, disminuir la ansiedad y favorecer un descanso profundo y reparador. Ideal para usar antes de dormir o en momentos de estrés.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-dulces-suenos.jpg', 13],
    ['in-inmune', 'Inmune', 'inhaladores', '1.5 ml', 150,
     'Contiene: Romero, eucalipto y menta. Una mezcla estimulante que fortalece las defensas naturales, apoya el sistema respiratorio y ayuda a prevenir infecciones. Ideal para cambios de clima, temporadas de resfriados o cuando se necesita un refuerzo inmunológico.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-inmune.jpg', 14],
    ['in-enfoque', 'Enfoque', 'inhaladores', '1.5 ml', 150,
     'Contiene: Limón, hierbabuena, romero, cedro. Una mezcla diseñada para mejorar la concentración, la memoria y la claridad mental. Favorece la productividad y ayuda a mantener el enfoque durante actividades que requieren atención.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-enfoque.jpg', 15],
    ['in-armonia-y-bienestar', 'Armonía y bienestar', 'inhaladores', '1.5 ml', 150,
     'Contiene: Limón, bergamota, naranja, mandarina y toronja. Una mezcla brillante que ayuda a mejorar el ánimo, reducir el estrés leve y promover una sensación de equilibrio emocional. Ideal para crear un estado de bienestar y ligereza durante el día.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-armonia-y-bienestar.jpg', 16],
    ['in-serenidad', 'Serenidad', 'inhaladores', '1.5 ml', 150,
     'Contiene: Lavanda, mandarina, albahaca y cedro. una mezcla calmante que ayuda a reducir el estrés, la ansiedad y la sobrecarga emocional. Favorece el equilibrio interno y promueve una sensación de paz y tranquilidad.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-serenidad.jpg', 17],
    ['in-alegria', 'Alegría', 'inhaladores', '1.5 ml', 150,
     'Contiene: Rosas, bergamota, mandarina, ylang ylang, limón, geranio. Una mezcla luminosa que ayuda a elevar el ánimo, reducir la tristeza y promover una sensación de bienestar emocional. Ideal para momentos de desánimo o cuando se busca recuperar energía positiva.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-alegria.jpg', 18],
    ['in-motivacion', 'Motivación', 'inhaladores', '1.5 ml', 150,
     'Contiene: Ylang ylang, lavanda, melissa, hierbabuena. Una mezcla diseñada para renovar la energía, equilibrar las emociones y recuperar la motivación en momentos de cansancio o apatía.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-motivacion.jpg', 19],
    ['in-zen', 'Zen', 'inhaladores', '1.5 ml', 150,
     'Contiene: Lemongrass, geranio, incienso, mandarina. Una mezcla diseñada para promover el equilibrio emocional, calmar la mente y liberar la tensión. Ideal para momentos de estrés, meditación o cuando se busca reconectar con el presente.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-zen.jpg', 20],
    ['in-proteccion', 'Protección', 'inhaladores', '1.5 ml', 150,
     'Contiene: Clavo, canela, eucalipto, romero, limón. una mezcla purificante que ayuda a fortalecer el sistema inmunológico y a limpiar energéticamente. Ideal para épocas de enfermedad, cambios de clima o ambientes cargados.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-proteccion.jpg', 21],
    ['in-aura', 'Aura', 'inhaladores', '1.5 ml', 150,
     'Contiene: Ylang ylang, rosas, melissa, sándalo, geranio. una mezcla diseñada para promover la conexión emocional, la armonía y el equilibrio energético. Ideal para momentos de introspección, meditación o cuando se busca elevar el estado de ánimo.',
     '', 'No introducir dentro de la nariz. Evitar contacto con ojos y mucosas. Suspender su uso en caso de irritación o sensibilidad. No sustituye tratamientos médicos o psicológicos.', 'in-aura.jpg', 22],
    ['ve-almendras-dulces', 'Almendras dulces', 'vehiculares', '250 ml', 375,
     '',
     '', '', '', 10],
    ['ve-argan', 'Argán', 'vehiculares', '250 ml', 1650,
     '',
     '', '', '', 11],
    ['ve-jojoba', 'Jojoba', 'vehiculares', '250 ml', 675,
     '',
     '', '', '', 12],
    ['ve-pepita-de-uva', 'Pepita de uva', 'vehiculares', '250 ml', 420,
     '',
     '', '', '', 13],
    ['ve-rosa-mosqueta', 'Rosa mosqueta', 'vehiculares', '250 ml', 1005,
     '',
     '', '', '', 14],
    ['ve-ricino', 'Ricino', 'vehiculares', '250 ml', 420,
     '',
     '', '', '', 15],
    ];
}
