<?php
/* ══════════════════════════════════════════════════════════
   ALMA DE MAR · Catálogo inicial de la tienda
   ──────────────────────────────────────────────────────────
   Es la lista de precios de la marca, tal cual, para sembrar
   la tabla `productos` la primera vez. A partir de ahí manda
   la base de datos: lo que se edite en el panel NO se pisa al
   volver a ejecutar el instalador (se usa INSERT ... ON
   DUPLICATE KEY UPDATE solo sobre los campos de catálogo).

   Cada fila:
     [id, nombre, categoría, presentación, precio, descripción, orden]

   El peso y las medidas NO van aquí: los pone el perfil de la
   categoría en api/envios.php, y solo se capturan a mano en el
   panel cuando una pieza se sale del molde.
   ══════════════════════════════════════════════════════════ */

declare(strict_types=1);

/* Los grupos de la tienda, en el orden en que salen en la página. */
function categoriasTienda(): array {
    return [
        ['id' => 'aceites',     'titulo' => 'Aceites esenciales',   'nota' => '10 ml',  'imagen' => 'aceites.jpg'],
        ['id' => 'sinergias',   'titulo' => 'Sinergias',            'nota' => 'Mezclas con propósito', 'imagen' => 'sinergias.jpg'],
        ['id' => 'inhaladores', 'titulo' => 'Inhaladores nasales',  'nota' => '1.5 ml', 'imagen' => 'inhaladores.jpg'],
        ['id' => 'brisas',      'titulo' => 'Brisas y repelente',   'nota' => '125 ml', 'imagen' => 'brisas.jpg'],
        ['id' => 'masaje',      'titulo' => 'Aceites para masaje',  'nota' => '250 ml', 'imagen' => 'masaje.jpg'],
        ['id' => 'vehiculares', 'titulo' => 'Aceites vehiculares',  'nota' => '250 ml', 'imagen' => 'aceites-coleccion.jpg'],
        ['id' => 'velas8',      'titulo' => 'Velas',                'nota' => '8 oz',   'imagen' => ''],
        ['id' => 'velas4',      'titulo' => 'Velas',                'nota' => '4 oz',   'imagen' => ''],
    ];
}

function catalogoInicial(): array {
    return [
    ['ae-naranja', 'Naranja', 'aceites', '10 ml', 340, '', 10],
    ['ae-toronja', 'Toronja', 'aceites', '10 ml', 380, '', 11],
    ['ae-mandarina', 'Mandarina', 'aceites', '10 ml', 480, '', 12],
    ['ae-limon', 'Limón', 'aceites', '10 ml', 380, '', 13],
    ['ae-bergamota', 'Bergamota', 'aceites', '10 ml', 400, '', 14],
    ['ae-lima', 'Lima', 'aceites', '10 ml', 380, '', 15],
    ['ae-albahaca', 'Albahaca', 'aceites', '10 ml', 340, '', 16],
    ['ae-anis', 'Anís', 'aceites', '10 ml', 480, '', 17],
    ['ae-clavo', 'Clavo', 'aceites', '10 ml', 380, '', 18],
    ['ae-canela', 'Canela', 'aceites', '10 ml', 380, '', 19],
    ['ae-curcuma', 'Cúrcuma', 'aceites', '10 ml', 500, '', 20],
    ['ae-romero', 'Romero', 'aceites', '10 ml', 380, '', 21],
    ['ae-menta', 'Menta', 'aceites', '10 ml', 380, '', 22],
    ['ae-hierbabuena', 'Hierbabuena', 'aceites', '10 ml', 500, '', 23],
    ['ae-lemongrass', 'Lemongrass', 'aceites', '10 ml', 380, '', 24],
    ['ae-jengibre', 'Jengibre', 'aceites', '10 ml', 560, '', 25],
    ['ae-oregano', 'Orégano', 'aceites', '10 ml', 540, '', 26],
    ['ae-cardamomo', 'Cardamomo', 'aceites', '10 ml', 780, '', 27],
    ['ae-enebro', 'Enebro', 'aceites', '10 ml', 700, '', 28],
    ['ae-laurel', 'Laurel', 'aceites', '10 ml', 780, '', 29],
    ['ae-pimienta-negra', 'Pimienta negra', 'aceites', '10 ml', 780, '', 30],
    ['ae-limon-italiano', 'Limón italiano', 'aceites', '10 ml', 800, '', 31],
    ['ae-salvia', 'Salvia', 'aceites', '10 ml', 540, '', 32],
    ['ae-tomillo', 'Tomillo', 'aceites', '10 ml', 380, '', 33],
    ['ae-eucalipto', 'Eucalipto', 'aceites', '10 ml', 380, '', 34],
    ['ae-geranio', 'Geranio', 'aceites', '10 ml', 540, '', 35],
    ['ae-rosas', 'Rosas', 'aceites', '10 ml', 1000, '', 36],
    ['ae-lavanda', 'Lavanda', 'aceites', '10 ml', 380, '', 37],
    ['ae-ylang-ylang', 'Ylang ylang', 'aceites', '10 ml', 500, '', 38],
    ['ae-incienso', 'Incienso', 'aceites', '10 ml', 780, '', 39],
    ['ae-sandalo', 'Sándalo', 'aceites', '10 ml', 540, '', 40],
    ['ae-cedro', 'Cedro', 'aceites', '10 ml', 380, '', 41],
    ['ae-cipres', 'Ciprés', 'aceites', '10 ml', 380, '', 42],
    ['ae-pino-siberiano', 'Pino siberiano', 'aceites', '10 ml', 500, '', 43],
    ['ae-arbol-de-te', 'Árbol de té', 'aceites', '10 ml', 380, '', 44],
    ['ae-patchouli', 'Patchouli', 'aceites', '10 ml', 500, '', 45],
    ['ae-citronela', 'Citronela', 'aceites', '10 ml', 340, '', 46],
    ['ae-melissa', 'Melissa', 'aceites', '10 ml', 780, '', 47],
    ['ae-mirra', 'Mirra', 'aceites', '10 ml', 700, '', 48],
    ['ae-neroli', 'Neroli', 'aceites', '10 ml', 780, '', 49],
    ['ae-manzanilla-alemana', 'Manzanilla alemana', 'aceites', '10 ml', 1200, '', 50],
    ['ae-palo-santo', 'Palo santo', 'aceites', '10 ml', 780, '', 51],
    ['ae-vetiver', 'Vetiver', 'aceites', '10 ml', 800, '', 52],
    ['si-respiracion', 'Respiración', 'sinergias', '10 ml', 430, '', 10],
    ['si-dulces-suenos', 'Dulces sueños', 'sinergias', '10 ml', 430, '', 11],
    ['si-vitalidad', 'Vitalidad', 'sinergias', '10 ml', 430, '', 12],
    ['si-inhala', 'Inhala +', 'sinergias', '10 ml', 430, '', 13],
    ['si-articulaciones', 'Articulaciones', 'sinergias', '10 ml', 430, '', 14],
    ['si-inmune', 'Inmune', 'sinergias', '10 ml', 430, '', 15],
    ['si-despierta', 'Despierta', 'sinergias', '10 ml', 430, '', 16],
    ['si-dolor-de-cabeza', 'Dolor de cabeza', 'sinergias', '10 ml', 430, '', 17],
    ['si-armonia-y-bienestar', 'Armonía y bienestar', 'sinergias', '10 ml', 430, '', 18],
    ['si-analgesia', 'Analgesia', 'sinergias', '10 ml', 430, '', 19],
    ['si-concentracion', 'Concentración', 'sinergias', '10 ml', 440, '', 20],
    ['si-mas-cabello', 'Más cabello', 'sinergias', '10 ml', 440, '', 21],
    ['si-fem', 'Fem', 'sinergias', '10 ml', 500, '', 22],
    ['si-antioxidante', 'Antioxidante', 'sinergias', '10 ml', 430, '', 23],
    ['si-super-boost', 'Súper boost', 'sinergias', '10 ml', 430, '', 24],
    ['si-serenidad', 'Serenidad', 'sinergias', '10 ml', 500, '', 25],
    ['si-redu-c', 'Redu-C', 'sinergias', '50 ml', 600, '', 26],
    ['si-varices', 'Várices', 'sinergias', '50 ml', 600, '', 27],
    ['si-digest', 'Digest', 'sinergias', '10 ml', 560, '', 28],
    ['si-mas-barba', 'Más barba', 'sinergias', '10 ml', 400, '', 29],
    ['si-enfoque', 'Enfoque', 'sinergias', '10 ml', 560, '', 30],
    ['si-slim', 'Slim', 'sinergias', '10 ml', 580, '', 31],
    ['si-serum-facial', 'Sérum facial', 'sinergias', '30 ml', 740, '', 32],
    ['si-pasion', 'Pasión', 'sinergias', '10 ml', 600, '', 33],
    ['si-amor', 'Amor', 'sinergias', '10 ml', 660, '', 34],
    ['si-motivacion', 'Motivación', 'sinergias', '10 ml', 600, '', 35],
    ['si-paz', 'Paz', 'sinergias', '10 ml', 600, '', 36],
    ['si-transformacion', 'Transformación', 'sinergias', '10 ml', 700, '', 37],
    ['si-alegria', 'Alegría', 'sinergias', '10 ml', 600, '', 38],
    ['si-aura', 'Aura', 'sinergias', '10 ml', 780, '', 39],
    ['si-proteccion', 'Protección', 'sinergias', '10 ml', 600, '', 40],
    ['si-abundancia', 'Abundancia', 'sinergias', '10 ml', 500, '', 41],
    ['si-zen', 'Zen', 'sinergias', '10 ml', 600, '', 42],
    ['v8-limon-satin', 'Limón Satín', 'velas8', '8 oz', 450, '', 10],
    ['v8-abrazo-al-alma', 'Abrazo al alma', 'velas8', '8 oz', 525, '', 11],
    ['v8-paz', 'Paz', 'velas8', '8 oz', 525, '', 12],
    ['v8-dulce-hogar', 'Dulce Hogar', 'velas8', '8 oz', 450, '', 13],
    ['v8-viento-de-otono', 'Viento de otoño', 'velas8', '8 oz', 450, '', 14],
    ['v8-estela-de-verano', 'Estela de verano', 'velas8', '8 oz', 450, '', 15],
    ['v8-entre-flores', 'Entre flores', 'velas8', '8 oz', 525, '', 16],
    ['v8-luz-de-eucalipto', 'Luz de eucalipto', 'velas8', '8 oz', 450, '', 17],
    ['v8-media-noche', 'Media noche', 'velas8', '8 oz', 450, '', 18],
    ['v8-himalaya', 'Himalaya', 'velas8', '8 oz', 450, '', 19],
    ['v8-astral', 'Astral', 'velas8', '8 oz', 525, '', 20],
    ['v8-mediterraneo', 'Mediterráneo', 'velas8', '8 oz', 525, '', 21],
    ['v4-limon-satin', 'Limón Satín', 'velas4', '4 oz', 270, '', 10],
    ['v4-abrazo-al-alma', 'Abrazo al alma', 'velas4', '4 oz', 295, '', 11],
    ['v4-paz', 'Paz', 'velas4', '4 oz', 295, '', 12],
    ['v4-dulce-hogar', 'Dulce Hogar', 'velas4', '4 oz', 270, '', 13],
    ['v4-viento-de-otono', 'Viento de otoño', 'velas4', '4 oz', 270, '', 14],
    ['v4-estela-de-verano', 'Estela de verano', 'velas4', '4 oz', 270, '', 15],
    ['v4-entre-flores', 'Entre flores', 'velas4', '4 oz', 295, '', 16],
    ['v4-luz-de-eucalipto', 'Luz de eucalipto', 'velas4', '4 oz', 270, '', 17],
    ['v4-media-noche', 'Media noche', 'velas4', '4 oz', 270, '', 18],
    ['v4-himalaya', 'Himalaya', 'velas4', '4 oz', 270, '', 19],
    ['v4-astral', 'Astral', 'velas4', '4 oz', 295, '', 20],
    ['v4-mediterraneo', 'Mediterráneo', 'velas4', '4 oz', 295, '', 21],
    ['ma-dulces-suenos', 'Dulces sueños', 'masaje', '250 ml', 450, 'Ideal para masajes relajantes. Nutre la piel y deja una fragancia dulce y cítrica que envuelve los sentidos, convirtiendo cada aplicación en un momento de serenidad y renovación.', 10],
    ['ma-analgesia', 'Analgesia', 'masaje', '250 ml', 450, 'Ideal para terapéuticos o después de un día agotador: ayuda a relajar el cuerpo y despejar la mente. Su textura ligera y de rápida absorción deja la piel suave, hidratada y con una fragancia herbal envolvente.', 11],
    ['ma-despierta', 'Despierta', 'masaje', '250 ml', 450, 'Ideal para masajes energetizantes o después de una jornada intensa. Ayuda a aliviar la fatiga, dejando la piel suave y con una fragancia fresca y estimulante.', 12],
    ['br-dulces-suenos', 'Dulces sueños', 'brisas', '125 ml', 285, 'Aceite esencial de naranja, mandarina y lavanda. Ayuda a reducir el estrés, la ansiedad y el insomnio, y crea una atmósfera relajante y reconfortante. Ideal para usar antes de dormir en la almohada, sábanas o habitación.', 10],
    ['br-armonia-y-bienestar', 'Armonía y bienestar', 'brisas', '125 ml', 285, 'Aceite esencial de limón, naranja, bergamota, toronja y mandarina. Promueve el bienestar emocional y el equilibrio interior; ayuda a disolver el estrés y la negatividad. Ideal para espacios luminosos y frescos.', 11],
    ['br-serenidad', 'Serenidad', 'brisas', '125 ml', 330, 'Aceite esencial de lavanda, cedro, mandarina y albahaca. Promueve un estado de serenidad, calma y equilibrio emocional. Ideal para momentos de descanso, meditación o conexión espiritual suave.', 12],
    ['br-despierta', 'Despierta', 'brisas', '125 ml', 285, 'Aceite esencial de limón y eucalipto. Aporta energía desde la primera hora del día, favorece la concentración y la claridad mental, y ayuda a combatir la fatiga y la somnolencia.', 13],
    ['br-proteccion', 'Protección', 'brisas', '125 ml', 330, 'Aceite esencial de clavo, canela, limón, romero y eucalipto. Protege energéticamente el cuerpo y los espacios, purifica y despeja energías densas, y fortalece el campo energético personal.', 14],
    ['br-abundancia', 'Abundancia', 'brisas', '125 ml', 285, 'Aceite esencial de lavanda, cedro y canela. Promueve la abundancia material y emocional, ayudando a atraer oportunidades positivas. Equilibra el chakra Muladhara (raíz), promoviendo seguridad, confianza y estabilidad.', 15],
    ['br-repelente-adios-mosqu', 'Repelente adiós mosquitos', 'brisas', '125 ml', 300, 'Brisa repelente de aceites esenciales, sin ingredientes sintéticos agresivos.', 16],
    ['in-dolor-de-cabeza', 'Dolor de cabeza', 'inhaladores', '1.5 ml', 150, '', 10],
    ['in-respiracion', 'Respiración', 'inhaladores', '1.5 ml', 150, '', 11],
    ['in-despierta', 'Despierta', 'inhaladores', '1.5 ml', 150, '', 12],
    ['in-dulces-suenos', 'Dulces sueños', 'inhaladores', '1.5 ml', 150, '', 13],
    ['in-inmune', 'Inmune', 'inhaladores', '1.5 ml', 150, '', 14],
    ['in-enfoque', 'Enfoque', 'inhaladores', '1.5 ml', 150, '', 15],
    ['in-armonia-y-bienestar', 'Armonía y bienestar', 'inhaladores', '1.5 ml', 150, '', 16],
    ['in-serenidad', 'Serenidad', 'inhaladores', '1.5 ml', 150, '', 17],
    ['in-alegria', 'Alegría', 'inhaladores', '1.5 ml', 150, '', 18],
    ['in-motivacion', 'Motivación', 'inhaladores', '1.5 ml', 150, '', 19],
    ['in-zen', 'Zen', 'inhaladores', '1.5 ml', 150, '', 20],
    ['in-proteccion', 'Protección', 'inhaladores', '1.5 ml', 150, '', 21],
    ['in-aura', 'Aura', 'inhaladores', '1.5 ml', 150, '', 22],
    ['ve-almendras-dulces', 'Almendras dulces', 'vehiculares', '250 ml', 375, '', 10],
    ['ve-argan', 'Argán', 'vehiculares', '250 ml', 1650, '', 11],
    ['ve-jojoba', 'Jojoba', 'vehiculares', '250 ml', 675, '', 12],
    ['ve-pepita-de-uva', 'Pepita de uva', 'vehiculares', '250 ml', 420, '', 13],
    ['ve-rosa-mosqueta', 'Rosa mosqueta', 'vehiculares', '250 ml', 1005, '', 14],
    ['ve-ricino', 'Ricino', 'vehiculares', '250 ml', 420, '', 15],
    ];
}
